---
version: '3'
services:
  authelia-backend:
    image: authelia:dist
    volumes:
      - '../..:/authelia'
    labels:
      # Traefik 1.x
      - 'traefik.frontend.rule=Host:login.example.com;PathPrefix:/api,/locales'
      - 'traefik.protocol=https'
      # Traefik 2.x
      - 'traefik.http.routers.authelia_backend.rule=Host(`login.example.com`) && PathPrefix(`/.well-known`) || Host(`login.example.com`) && PathPrefix(`${PathPrefix}/.well-known`) || Host(`login.example.com`) && PathPrefix(`/api`) || Host(`login.example.com`) && PathPrefix(`${PathPrefix}/api`) || Host(`login.example.com`) && PathPrefix(`/locales`) || Host(`login.example.com`) && PathPrefix(`${PathPrefix}/locales`) || Host(`login.example.com`) && Path(`/jwks.json`) || Host(`login.example.com`) && Path(`${PathPrefix}/jwks.json`)'  # yamllint disable-line rule:line-length
      - 'traefik.http.routers.authelia_backend.entrypoints=https'
      - 'traefik.http.routers.authelia_backend.tls=true'
      - 'traefik.http.services.authelia_backend.loadbalancer.server.scheme=https'
      - 'traefik.http.services.authelia_backend.passHostHeader=true'
    healthcheck:
      disable: true
    environment:
      - AUTHELIA_SERVER_DISABLE_HEALTHCHECK=true
      - ENVIRONMENT=dev
    restart: always
    networks:
      authelianet:
        ipv4_address: 192.168.240.50
...
