---
runner:
  authelia:
    cmd: go run ./cmd/authelia-scripts gen && git --no-pager diff
    format: diff
    level: error
  golangci:
    cmd: golangci-lint run
    errorformat:
      - '%E%f:%l:%c: %m'
      - '%E%f:%l: %m'
      - '%C%.%#'
    level: error
  eslint:
    cmd: cd web && eslint -f rdjson '*/**/*.{js,ts,tsx}'
    format: rdjson
    level: error
  yamllint:
    cmd: yamllint --format parsable .
    errorformat:
      - '%f:%l:%c: %m'
    level: warning
...
