language: go
required: sudo
go:
- '1.13'
services:
- docker
- ntp
- xvfb
addons:
  chrome: stable
  apt:
    sources:
    - google-chrome
    packages:
    - libgif-dev
    - google-chrome-stable

before_script:
- curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
- nvm install v11 && nvm use v11 && npm i
script:
- "source bootstrap.sh"
- "authelia-scripts ci"
after_success:
- "authelia-scripts docker publish"

# TODO(c.michaud): publish built artifact on Github.

notifications:
  email:
    recipients:
    - clement.michaud34@gmail.com
    on_success: change
    on_failure: always
