###############################################################
#                Authelia minimal configuration               #
###############################################################

authentication_backend:
  file:
    # The path to the database file. The file is at the root of the repo.
    path: /etc/authelia/users_database.yml

session:
  # The secret to encrypt the session cookies with.
  secret: unsecure_session_secret

  # The domain to protect.
  # Note: Authelia must also be served by that domain.
  domain: example.com
