---
files:
  - source: /internal/server/locales/en/*
    translation: /internal/server/locales/%locale%/%original_file_name%
  - source: /internal/server/locales/en/*
    translation: /internal/server/locales/%locale_with_underscore%/%original_file_name%
...
