---
pull_request_title: "i18n: update translations"
files:
#  - source: /internal/server/locales/en/*
#    translation: /internal/server/locales/%locale%/%original_file_name%
#    skip_untranslated_strings: true
#    skip_untranslated_files: true
  - source: /internal/server/locales/en/*
    translation: /internal/server/locales/%locale_with_underscore%/%original_file_name%
    skip_untranslated_strings: true
    skip_untranslated_files: true
...
