version: '2'
services:
  authelia:
    build: .
    restart: always
    volumes:
      - ./config.minimal.yml:/etc/authelia/config.yml:ro
      - ./users_database.test.yml:/etc/authelia/users_database.yml:rw
      - /tmp/authelia:/tmp/authelia
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    networks:
      - example-network
