version: "3"
services:
  authelia-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "/tmp/authelia:/tmp/authelia"
    environment:
      - ENVIRONMENT=dev
    restart: always
    networks:
      authelianet:
        ipv4_address: 192.168.240.50
