version: '2'
services:
  authelia:
    image: authelia:dist
    restart: always
    volumes:
      - ./test/suites/docker-image/config.yml:/etc/authelia/config.yml:ro
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    depends_on: 
      - redis
    networks:
      - authelianet