version: "3"
services:
  authelia-backend:
    build:
      context: example/compose/authelia
      dockerfile: Dockerfile.backend
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        TRAVIS: ${TRAVIS}
    command: /resources/entrypoint-backend.sh
    working_dir: /app
    volumes:
      - "./example/compose/authelia/resources/:/resources"
      - ".:/app"
      - "${GOPATH}:/go"
    labels:
      - traefik.frontend.rule=Host:login.example.com;PathPrefix:/api
      - traefik.port=9091
    environment:
      - ENVIRONMENT=dev
      - CI=${CI}
      - TRAVIS=${TRAVIS}
    networks:
      authelianet:
        ipv4_address: 192.168.240.50