version: "3"
services:
  authelia-backend:
    build:
      context: example/compose/authelia
      dockerfile: Dockerfile.backend
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    command: /resources/entrypoint.sh
    working_dir: /app
    volumes:
      - "./example/compose/authelia/resources/:/resources"
      - ".:/app"
      - "${GOPATH}:/go"
    environment:
      - ENVIRONMENT=dev
    networks:
      authelianet:
        ipv4_address: 192.168.240.50
