version: "3"
services:
  authelia-frontend:
    build:
      context: example/compose/authelia
      dockerfile: Dockerfile.frontend
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    command: /resources/entrypoint-frontend.sh
    working_dir: /app
    volumes:
      - "./example/compose/authelia/resources/:/resources"
      - "./web:/app"
    networks:
      - authelianet