version: '3'
services:
  authelia-backend:
    build:
      context: example/compose/authelia
      dockerfile: Dockerfile.backend
    command: /resources/entrypoint.sh
    working_dir: /app
    volumes:
      - "./example/compose/authelia/resources/:/resources"
      - ".:/app"
      - "${GOPATH}:/go"
      - "/tmp/authelia:/tmp/authelia"
    environment:
      - SUITE_PATH=${SUITE_PATH}
      - ENVIRONMENT=dev
    networks:
      authelianet:
        ipv4_address: 192.168.240.50
