version: '3'
services:
  authelia-frontend:
    build:
      context: example/compose/authelia
      dockerfile: Dockerfile.frontend
    command: npm run start
    working_dir: /app
    volumes:
      - "./web:/app"
    networks:
      - authelianet
