---
server:
  host: '0.0.0.0'
  port: 9091
  path: "auth"

authentication_backend:
  ldap:
    url: 'ldap://127.0.0.1'

storage:
  mysql:
    host: 127.0.0.1
    port: 3306
  postgres:
    host: 127.0.0.1
    port: 5432

notifier:
  smtp:
    host: 127.0.0.1
    port: 1025
...
