---
version: '3'
services:
  oidc-client:
    image: ghcr.io/authelia/oidc-tester-app:master-2a82ab3
    command: /entrypoint.sh
    depends_on:
      - authelia-backend
    volumes:
      - ./example/compose/oidc-client/entrypoint.sh:/entrypoint.sh
    networks:
      - authelianet
...
