steps:
  - label: ":hammer_and_wrench: Build & Test"
    command: "authelia-scripts --log-level debug ci"
    agents:
      upload: "fast"
    artifact_paths:
      - "dist.tar.gz"
      - "web.tar.gz"

  - wait

  - label: ":chrome: Integration Tests"
    command: ".buildkite/steps/e2etests.sh | buildkite-agent pipeline upload"

  - wait

  - label: ":docker: Image Builds"
    command: ".buildkite/steps/buildimages.sh | buildkite-agent pipeline upload"
    branches: "master buildkite v*"

  - wait

  - label: ":docker: Deploy Manifests"
    command: "authelia-scripts docker push-manifest"
    branches: "master buildkite v*"
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"

  - label: ":github: Deploy Artifacts"
    command: ".buildkite/steps/ghartifacts.sh"
    agents:
      upload: "fast"
    if: build.tag != null