steps:
  - command: "authelia-scripts --log-level debug ci"
    label: ":hammer_and_wrench: Build and test Authelia"
    agents:
      build: "true"
    artifact_paths:
      - "dist.tar.gz"
      - "web.tar.gz"

  - wait

  - command: ".buildkite/steps/e2etests.sh | buildkite-agent pipeline upload"
    label: ":chrome: End-to-end suite tests"

  - wait

  - command: ".buildkite/steps/buildimages.sh | buildkite-agent pipeline upload"
    label: ":docker: Image builds"
    branches: "master buildkite"
    artifact_paths:
      - "authelia-linux-*"

  - wait

  - command: "authelia-scripts docker push-manifest"
    label: ":docker: Manifest deploy"
    branches: "master buildkite"
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"

  - commands: ".buildkite/steps/ghartifacts.sh"
    label: ":github: Publish binary artifacts"
    if: build.tag != null