steps:
  - label: ":hammer_and_wrench: Unit Test"
    command: "authelia-scripts --log-level debug ci"
    if: build.message !~ /^\[DOCS\]/

  - wait:
    if: build.message !~ /^\[DOCS\]/

  - label: ":docker: Image Builds"
    command: ".buildkite/steps/buildimages.sh | buildkite-agent pipeline upload"
    depends_on: ~
    if: build.message !~ /^\[DOCS\]/

  - wait:
    if: build.message !~ /^\[DOCS\]/

  - label: ":chrome: Integration Tests"
    command: ".buildkite/steps/e2etests.sh | buildkite-agent pipeline upload"
    depends_on:
      - "build-docker-amd64"
    if: build.message !~ /^\[DOCS\]/