steps:
  - label: ":hammer_and_wrench: Build & Test"
    command: "authelia-scripts --log-level debug ci"
    artifact_paths:
      - "dist.tar.zst"
      - "web.tar.zst"
    key: "build"

  - wait

  - label: ":chrome: Integration Tests"
    command: ".buildkite/steps/e2etests.sh | buildkite-agent pipeline upload"
    key: "test"

  - wait:
    if: build.branch == "master" || build.branch =~ /^v/

  - label: ":docker: Image Builds"
    command: ".buildkite/steps/buildimages.sh | buildkite-agent pipeline upload"
    agents:
      build: "true"
    branches: "master v*"
    depends_on:
      - "build"
    key: "build-docker"

  - wait:
    if: build.branch == "master" || build.branch =~ /^v/

  - label: ":docker: Image Deployments"
    command: ".buildkite/steps/deployimages.sh | buildkite-agent pipeline upload"
    branches: "master v*"
    depends_on:
      - "test"
      - "build-docker"

  - wait:
    if: build.branch == "master" || build.branch =~ /^v/

  - label: ":docker: Deploy Manifests"
    command: "authelia-scripts docker push-manifest"
    branches: "master v*"
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"

  - label: ":github: Deploy Artifacts"
    command: ".buildkite/steps/ghartifacts.sh"
    agents:
      upload: "fast"
    depends_on: "build-docker"
    if: build.tag != null