steps:
  - command: "authelia-scripts --log-level debug ci"
    label: ":hammer_and_wrench: Build & Test"
    agents:
      upload: "fast"
    artifact_paths:
      - "dist.tar.gz"
      - "web.tar.gz"

  - wait

  - command: ".buildkite/steps/e2etests.sh | buildkite-agent pipeline upload"
    label: ":chrome: Integration Tests"

  - wait

  - command: ".buildkite/steps/buildimages.sh | buildkite-agent pipeline upload"
    label: ":docker: Image Builds"
    branches: "master buildkite"
    artifact_paths:
      - "authelia-linux-*"

  - wait

  - command: "authelia-scripts docker push-manifest"
    label: ":docker: Deploy Manifests"
    branches: "master buildkite"
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"

  - commands: ".buildkite/steps/ghartifacts.sh"
    label: ":github: Deploy Artifacts"
    if: build.tag != null