steps:
  - command: ".buildkite/steps/buildandtest.sh"
    name: ":hammer_and_wrench: Build & Test"
    agents:
      build: "true"
    artifact_paths:
      - "dist.tar.gz"
      - "web.tar.gz"

  - wait

  - command: ".buildkite/steps/e2etests.sh | buildkite-agent pipeline upload"
    name: ":chrome: End-to-end suite tests"

  - wait

  - command: ".buildkite/steps/buildimages.sh | buildkite-agent pipeline upload"
    label: ":docker: Image builds"
    branches: "master buildkite"

  - wait

  - command: "authelia-scripts docker push-manifest"
    label: ":docker: Manifest deploy"
    branches: "master buildkite"
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"