## STATIC CONFIGURATION
log:
  level: DEBUG
  filePath: /var/log/traefik.log

accessLog:
  filePath: /var/log/traefik-access.log
  bufferingSize: 1000

api:
  dashboard: true

providers:
  file:
    filename: /etc/traefik/traefik.yml
    watch: true

  docker:
    endpoint: "unix:///var/run/docker.sock"

entryPoints:
  http:
    address: ":80"

  https:
    address: ":8080"

http:
  middlewares:
    authelia:
      forwardAuth:
        trustForwardHeaders: true
        authResponseHeaders:
          - X-Forwarded-User
        address: http://authelia-backend:9091/api/verify?rd=https://login.example.com:8080/
        tls:
          insecureSkipVerify: true