services:
  swag:
    image: lscr.io/linuxserver/swag
    cap_add:
      - NET_ADMIN
    container_name: swag
    networks:
      proxy: {}
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: Australia/Melbourne
    volumes:
      - './data/proxy/swag:/config'
    ports:
      - '443:443/tcp'
      - '80:80/tcp'
    restart: 'unless-stopped'
