version: "3"
services:
  authelia-backend:
    volumes:
      - "./internal/suites/Postgres/configuration.yml:/etc/authelia/configuration.yml:ro"
      - "./internal/suites/Postgres/users.yml:/var/lib/authelia/users.yml"
