---
version: '3'
services:
  authelia-backend:
    volumes:
      - './CLI/configuration.yml:/config/configuration.yml:ro'
      - './CLI/cli.yml:/config/cli.yml:ro'
      - './CLI/users.yml:/config/users.yml'
      - './common/ssl:/config/ssl:ro'
      - '/tmp:/tmp'
    user: ${USER_ID}:${GROUP_ID}
...
