---
version: '3'
services:
  envoy:
    image: envoyproxy/envoy:v1.25.1
    volumes:
      - ./example/compose/envoy/envoy.yaml:/etc/envoy/envoy.yaml
      - ./common/pki:/pki
    networks:
      authelianet:
        ipv4_address: 192.168.240.100
...
