---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
  # yamllint disable-line rule:indentation
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registrycache.internal:5000"]
      endpoint = ["http://registrycache.internal:5000"]
...
