defaultEntryPoints = ["http", "https"]
logLevel = "DEBUG"

[traefikLog]
  filePath = "/var/log/traefik.log"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":8080"
    [entryPoints.https.tls]
  [entryPoints.api]
  address = ":8081"

[file]

[frontends]
  [frontends.authelia_api]
  backend = "authelia_api_backend"
  [frontends.authelia_api.routes.route0]
    rule = "Host:login.example.com; PathPrefix:/api;"

  [frontends.authelia_front]
  backend = "authelia_front_backend"
  [frontends.authelia_front.routes.route0]
    rule = "Host:login.example.com"
    
[backends]
  [backends.authelia_api_backend]
    [backends.authelia_api_backend.servers.server]
    url = "http://authelia-backend:9091"

  [backends.authelia_front_backend]
    [backends.authelia_front_backend.servers.server]
    url = "http://authelia-frontend:3000"

[api]
# This is exposed via a subdomain and a proxy
entryPoint = "api"
dashboard = true

[docker]
# Docker server endpoint. Can be a tcp or a unix socket endpoint.
endpoint = "unix:///var/run/docker.sock"
# network = "traefik_default"

# Default domain used.
# Can be overridden by setting the "traefik.domain" label on a container.
domain = "localhost"

# Enable watch docker changes
watch = true
