version: '3'
services:
  authelia-backend:
    environment:
      - AUTHELIA_JWT_SECRET=very_important_secret
      - AUTHELIA_SESSION_SECRET=unsecure_session_secret
    volumes:
      - './internal/suites/Standalone/configuration.yml:/etc/authelia/configuration.yml:ro'
      - './internal/suites/Standalone/users.yml:/var/lib/authelia/users.yml'