[build]
  publish = "public"
  functions = "functions"

[build.environment]
  NODE_VERSION = "20.10.0"
  NPM_VERSION = "10.2.3"

[context.production]
  command = "pnpm build"

[context.deploy-preview]
  command = "pnpm build -- -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "pnpm build -- -b $DEPLOY_PRIME_URL"

[context.next]
  command = "pnpm build"

[context.next.environment]
  HUGO_ENV = "next"

[dev]
  framework = "#custom"
  command = "pnpm dev"
  targetPort = 1313
  port = 8888
  publish = "public"
  autoLaunch = false

# Redirects and rewrites — https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file


