version: "3"
services:
  authelia-backend:
    volumes:
      - "./internal/suites/DuoPush/configuration.yml:/etc/authelia/configuration.yml:ro"
      - "./internal/suites/DuoPush/users.yml:/var/lib/authelia/users.yml"
