---
version: '3'
services:
  caddy:
    build: ./example/compose/caddy/
    volumes:
      - ./example/compose/caddy/Caddyfile:/etc/caddy/Caddyfile
    networks:
      authelianet:
        ipv4_address: 192.168.240.100
...
